use_frameworks!

platform :ios, '8.0'

target 'JTBaseListViewLib_Example' do
  pod 'JTBaseListViewLib', :path => '../'

  target 'JTBaseListViewLib_Tests' do
    inherit! :search_paths

    
  end
end
